### ISSUE TITLE
Multiple instances of motion.nix?

### ISSUE THREAD

**Issue by mjakefranklin** [bjornfor/nixos-config#6]
I'm trying to implement Motion for a few cameras under NixOS, and I came across your motion.nix service definition.  I'm a bit new to NixOS, but it appears that Motion needs separate config files for each camera defined.  How does this work with this service?  Is there a way to define multiple instances?  Motion's documentation states that each camera needs a separate config file, but I only see the option for one config.

Thanks!

**Comment by bjornfor** [comment]
My motion module runs a motion process with its own motion.conf for each camera (an instance).

You can se the per-instance definition [here](https://github.com/bjornfor/nixos-config/blob/a95e514599394f3837ae831f13642f8ff5334a54/options/motion.nix#L18-L38). It gets applied to each `motion.instances.<name>` definition.

If you like motion, you might also be interested in this [NixOS module for motioneye](https://gist.github.com/peterhoeg/f9000a258afb8b73a6a427475cef9116).

**Comment by mjakefranklin** [comment]
Perfect, everything is working great now, thanks!
